# Generated by Django 2.2.7 on 2019-12-04 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoinUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=8, verbose_name='名字')),
                ('first_name', models.CharField(max_length=32, verbose_name='名前')),
                ('read_last_name', models.CharField(max_length=16, verbose_name='名字(カナ)')),
                ('read_first_name', models.CharField(max_length=32, verbose_name='名前(カナ)')),
                ('birthday', models.DateField(verbose_name='生年月日')),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, '男性'), (2, '女性')], default=1, verbose_name='性別')),
                ('phone_number', models.CharField(help_text='ハイフン無しで入力してください', max_length=11, verbose_name='電話番号')),
                ('postal_code', models.CharField(help_text='ハイフン無しで入力してください', max_length=7, verbose_name='郵便番号')),
                ('street_address', models.CharField(help_text='郵便番号を入力することで市町村までが自動で入力されます', max_length=64, verbose_name='住所')),
                ('profession', models.PositiveSmallIntegerField(choices=[(1, '高校生'), (2, 'その他')], default=1, verbose_name='職業')),
                ('high_school_name', models.CharField(blank=True, help_text='例) 専門学校岡山情報ビジネス学院', max_length=32, null=True, verbose_name='高校名')),
                ('school_year', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1年'), (2, '2年'), (3, '3年'), (4, '4年')], null=True, verbose_name='学年')),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], null=True, verbose_name='卒業予定年')),
                ('graduate', models.BooleanField(default=False, verbose_name='高校卒業済み')),
                ('certification', models.BooleanField(default=False, verbose_name='高認取得済み')),
                ('department', models.PositiveSmallIntegerField(choices=[(1, '医療福祉事務学科'), (2, '診療情報管理士学科'), (3, 'ホテル・ブライダル学科'), (4, '経営アシスト学科'), (5, '公務員・公務員速修学科'), (6, '保育学科'), (7, '情報スペシャリスト学科'), (8, '情報システム学科'), (9, 'ゲームクリエイター・ゲームプログラマー学科'), (10, 'データマーケター学科'), (11, 'ネット・動画クリエイター学科'), (12, 'CGデザイン学科')], default=1, verbose_name='参加希望学科')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日')),
            ],
            options={
                'verbose_name_plural': '参加ユーザー',
                'db_table': 'join_user',
            },
        ),
    ]
