# Generated by Django 2.2.7 on 2019-12-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinuser',
            name='certification',
            field=models.BooleanField(choices=[(True, 'はい'), (False, 'いいえ')], default=False, verbose_name='高認取得済み'),
        ),
        migrations.AlterField(
            model_name='joinuser',
            name='graduate',
            field=models.BooleanField(choices=[(True, 'はい'), (False, 'いいえ')], default=False, verbose_name='高校卒業済み'),
        ),
    ]
