# Generated by Django 2.2.7 on 2019-12-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_remove_joinuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinuser',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, '男性'), (2, '女性')], default=1, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='joinuser',
            name='profession',
            field=models.PositiveSmallIntegerField(choices=[(1, '学生'), (2, 'その他')], default=1, verbose_name='職業'),
        ),
        migrations.AlterField(
            model_name='joinuser',
            name='school_year',
            field=models.PositiveSmallIntegerField(choices=[(1, '1年'), (2, '2年'), (3, '3年'), (4, '4年')], default=None, verbose_name='学年'),
        ),
    ]
