# Generated by Django 2.2.7 on 2019-12-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_auto_20191208_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinuser',
            name='school_year',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1年'), (2, '2年'), (3, '3年')], null=True, verbose_name='学年'),
        ),
    ]
