# Generated by Django 2.2.7 on 2019-12-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_auto_20191202_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinuser',
            name='high_school_name',
            field=models.CharField(blank=True, default=None, max_length=32, verbose_name='高校名'),
        ),
    ]
