# Generated by Django 2.2.7 on 2019-12-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_auto_20191202_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinuser',
            name='certification',
            field=models.BooleanField(default=False, verbose_name='高認取得済み'),
        ),
        migrations.AlterField(
            model_name='joinuser',
            name='graduate',
            field=models.BooleanField(default=False, verbose_name='高校卒業済み'),
        ),
    ]
