# Generated by Django 2.2.7 on 2019-12-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_auto_20191202_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinuser',
            name='graduation_year',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], null=True, verbose_name='卒業予定年'),
        ),
        migrations.AlterField(
            model_name='joinuser',
            name='high_school_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='高校名'),
        ),
        migrations.AlterField(
            model_name='joinuser',
            name='school_year',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1年'), (2, '2年'), (3, '3年'), (4, '4年')], null=True, verbose_name='学年'),
        ),
    ]
