# Generated by Django 2.2.7 on 2019-12-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0006_auto_20191203_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinuser',
            name='high_school_name',
            field=models.CharField(blank=True, help_text='例) 専門学校岡山情報ビジネス学院', max_length=32, null=True, verbose_name='高校名'),
        ),
    ]
