# Generated by Django 2.2.7 on 2019-12-02 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='学科名')),
                ('school_year', models.PositiveSmallIntegerField(verbose_name='学年')),
                ('description', models.TextField(max_length=255, verbose_name='学科概要')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日')),
            ],
            options={
                'verbose_name_plural': '学科',
                'db_table': 'department',
            },
        ),
    ]
